# Generated by Django 4.1.5 on 2023-02-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing_cost',
            name='prices3',
            field=models.CharField(default=12, max_length=255, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housing_cost',
            name='prices4',
            field=models.CharField(default=3424, max_length=255, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
